/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {
    
    private Agenda agenda;

    public static void main(String[] args) {
    }
}
