/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.awt.Color;

public class App {

    // public static final int DOMINGO = 0;

    public static void main(String[] args) {
        // int aula = DOMINGO; // ok
        // aula = -400; // não desejado

        DiasDaSemana aulaPOO = DiasDaSemana.QUINTA;
        // aulaPOO = -500; //não pode, é ENUM

        DiasDaSemana aula = DiasDaSemana.QUINTA;
        // aula = 10; ENUM!! não tem como

        switch (aula) {
            case DOMINGO:
                System.out.println("não tem aula");
                break;
            case SEGUNDA:
                System.out.println("não tem aula");
                break;
            case TERCA:
                System.out.println("tem aula");
                break;
            // case 1; é ENUM, não tem como
            default:
                break;
        }

        // na matriz de inteiros dá de usar enum, tijolo do tipo 1, 2 ou 3
        // enum TIJOLO1, TIJOLO2, VAZIO

    }
}
